"""auto update

Revision ID: 7dbc153a35c1
Revises: 40b8ad28d99b
Create Date: 2026-03-12 18:27:06.439988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dbc153a35c1'
down_revision: Union[str, Sequence[str], None] = '40b8ad28d99b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diagnosis_drafts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('answers', sa.String(), nullable=True),
    sa.Column('current_question', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnosis_drafts_id'), 'diagnosis_drafts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_diagnosis_drafts_id'), table_name='diagnosis_drafts')
    op.drop_table('diagnosis_drafts')
    # ### end Alembic commands ###