"""auto update

Revision ID: dee17b85b7ca
Revises: 8eafa680381f
Create Date: 2026-04-07 19:07:55.829453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dee17b85b7ca'
down_revision: Union[str, Sequence[str], None] = '8eafa680381f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('toss_payment_key', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('toss_order_id', sa.String(), nullable=True))
    op.drop_column('orders', 'stripe_session_id')
    op.drop_column('orders', 'stripe_payment_intent')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('stripe_payment_intent', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('stripe_session_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('orders', 'toss_order_id')
    op.drop_column('orders', 'toss_payment_key')
    # ### end Alembic commands ###